swagger: '2.0'
info:
  description: Audit service for swim meet stats
  version: 1.0.0
  title: Swim Meet Audit Service

paths:
  /log/race:
    get:
      summary: get race stats by offset
      operationId: app.race_stat_offset
      description: Gets offset of race stat
      produces:
      - application/json
      parameters:
      - in: query
        name: offset
        description: pass a value offset to return
        required: true
        type: integer
      responses:
        200:
          description: Reports found
          schema:
            type: array
            items:
              $ref: '#/definitions/RaceInformation'
        400:
          description: bad input parameters
          
  /log/athlete:
    get:
      summary: get earliest athlete entry stat
      operationId: app.get_earliest_athlete_stat
      description: Gets the earliest athlete stat
      produces:
      - application/json
      responses:
        200:
          description: Reports found
          schema:
            type: array
            items:
              $ref: '#/definitions/AthleteInformation'
        400:
          description: bad input parameters
          
definitions:
  RaceInformation:
    type: object
    required:
    - race_id
    - swim
    - distance
    - distance_measurement
    properties:
      race_id:
        type: string
        format: uuid
        example: d290f1ee-6c54-4b01-90e6-d701748f0851
      swim:
        type: string
        example: Freestyle
      distance:
        type: integer
        example: 400
      distance_measurement:
        type: string
        example: meters
  AthleteInformation:
    required:
    - first_name
    - last_name
    - age
    - height
    - weight
    properties:
      first_name:
        type: string
        example: Carson
      last_name:
        type: string
        example: Olafson
      age:
        type: integer
        example: 22
      height:
        type: integer
        example: 190
      weight:
        type: integer
        example: 181